### ISSUE TITLE
What is the difference between 2 branches？

### ISSUE THREAD

**Issue by Fu-Dayuan** [Gabesarch/HELPER#1]
I have read your work and thought it was a great job! I am curious that is there any big difference between the 2 branches? (It seems that most changes is removing annotation) Should I create 2 environments for these 2  branches? (or there is only a difference between code, the environments, data and checkpoints are the same so I can only establish a new folder to run edh?)

**Comment by Gabesarch** [comment]
Thank you for your interest in our work!

Yes, the environment, data, and checkpoints will be the same, so you do not need to re-create these. The main differences in the code are: 
1. For EDH, the agent is also given an action history, and we use it initialize our mapping and object tracking: https://github.com/Gabesarch/HELPER/blob/teach_edh/models/teach_eval_embodied_llm.py#L422-L647
2. We give the LLM the program already completed by the EDH action history for planning the current EDH instance: https://github.com/Gabesarch/HELPER/blob/teach_edh/models/agent/planner.py#L65-L71. This is also reflected in the [examples in the memory](https://github.com/Gabesarch/HELPER/tree/teach_edh/prompt/examples).

**Comment by Fu-Dayuan** [comment]
Thank you! I have another question: Have you attempted to employ "ground truth" to navigate the environment? (In other words, have you just tried to remove the use_llm_search in the python main.py and add "not args.use_gt_subgoals" in the "if" condition before replan?) I've noticed a significantly low performance with a score of approximately 7% and 14% on the valid-seen TFD dataset. This score is notably lower than your GPT-4 version. While I can think of a few instances where the ground truth may be inaccurate, the observed performance seems excessively low. Can you provide insights into this?

**Comment by Fu-Dayuan** [comment]
<img width="653" alt="1698682272505" src="https://github.com/Gabesarch/HELPER/assets/77482343/486cc6cb-b94a-409f-9ad2-6d74ec315d17">
I just debug a case in that. It seem a bug in navigator, since "navigate bread" will be execute like the picture. As a result it is too far to go to the bread. And there is a lot of log about "The receptacle is too full or too small to contain the held item." when the robot want to put item on a countertop

**Comment by Fu-Dayuan** [comment]
> <img alt="1698682272505" width="653" src="https://user-images.githubusercontent.com/77482343/279124008-486cc6cb-b94a-409f-9ad2-6d74ec315d17.png"> I just debug a case in that. It seem a bug in navigator, since "navigate bread" will be execute like the picture. As a result it is too far to go to the bread. And there is a lot of log about "The receptacle is too full or too small to contain the held item." when the robot want to put item on a countertop

Is there some settings about depth estimate? like add use_estimated_depth？

**Comment by Gabesarch** [comment]
Apologies, the `use_gt_subgoals` in the current code had not been updated. The most recent commit has the corrected code.

If you are indifferent to estimated vs. GT from simulator, see [here](https://github.com/Gabesarch/HELPER#ground-truth) for ways to add other ground truth elements to improve navigation and perception. 

Keep in mind though that the GT subgoals are the actions taken by the human demonstrator, and often contain unnecessary and sub-optimal interactions, as noted [here](https://arxiv.org/abs/2210.04443). Thus, the GT subgoals may not necessarily improve the performance of the agent.

**Comment by Fu-Dayuan** [comment]
> Apologies, the `use_gt_subgoals` in the current code had not been updated. The most recent commit has the corrected code.
> 
> If you are indifferent to estimated vs. GT from simulator, see [here](https://github.com/Gabesarch/HELPER#ground-truth) for ways to add other ground truth elements to improve navigation and perception.
> 
> Keep in mind though that the GT subgoals are the actions taken by the human demonstrator, and often contain unnecessary and sub-optimal interactions, as noted [here](https://arxiv.org/abs/2210.04443). Thus, the GT subgoals may not necessarily improve the performance of the agent.

that's true! I just used gpt-3.5 to test your code and found a 10+ SR score in TFD unseen(even higher than your report😂） which is higher than the GT. However I have another question, is there any bug in GC? My GC score is even lower than SR and I found a case (for example 6e26385c641764c7_fe5a.tfd.json) that has total_goal_conditions=0 in metrics. (if I just run these cases, the python will raise error like:

>  File "main.py", line 43, in <module>
>     main()
>   File "main.py", line 23, in main
>     run_teach()
>   File "./HELPER_TFD/models/teach_eval_embodied_llm.py", line 1249, in run_teach
>     aggregrated_metrics = aggregate_metrics(metrics, args)
>   File "./HELPER_TFD/teach/src/teach/eval/compute_metrics.py", line 88, in aggregate_metrics
>     pc = completed_goal_conditions / float(total_goal_conditions)
> ZeroDivisionError: float division by zero

 (maybe line is different from yours but I did not change anything about metrics). Maybe you will not count the GC  accomplished by exploration?

**Comment by Gabesarch** [comment]
The GC can be lower than SR due to how its computed. As mentioned in the Teach paper: "We follow ALFRED in using a macro-, rather than microaverage for Goal-Conditioned Success Rate". 

I have not observed that error for validation unseen, but have not run that episode in isolation.
